# Generated by Django 3.0.8 on 2020-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='body',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
